---
- name: crontab
  hosts: all
  tasks:
    - name: use cron job
      ansible.builtin.cron:
        name: "test"
        minute: "*/2"
        user: ec2-user
        job: logger "RH294 in progress"
        state: present
