---
- name: use template
  hosts: all
  tasks:
    - name: use template
      ansible.builtin.template:
        src: ./myhost.j2
        dest: /etc/myhosts

- name: delete from all
  hosts: all, !dev
  tasks:
    - name : delete file
      ansible.builtin.file:
        path: /etc/myhosts
        state: absent
