---
- name: Create hwreport
  hosts: all
  tasks:

    - name: copy from folder
      ansible.builtin.copy:
        src: ./hwreport.empty
        dest: /root/hwreport.txt

    - name: replace module
      ansible.builtin.replace:
        path: /root/hwreport.txt
        regexp: "{{ item.oldvalue }}"
        replace: "{{ item.newvalue }}"
      loop:

        - oldvalue: hostname
          newvalue: "{{ ansible_hostname | default('NONE') }}"
        - oldvalue: biosversion
          newvalue: "{{ ansible_bios_version| default('NONE') }}"
        - oldvalue: memory
          newvalue: "{{ ansible_memtotal_mb | default('NONE') }}"
        - oldvalue: vdasize
          newvalue: "{{ ansible_devices.vda.size | default('NONE') }}"
        - oldvalue: vdbsize
          newvalue: "{{ ansible_devices.vdb.size | default('NONE') }}"

